#!/bin/sh
#
# Updates the visual studio project file if there are any new files
# in src directory and adds it to the commit.
# (And checks for whitespace)

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Redirect output to stderr.
exec 1>&2

# The vs project update script updates files matching src/*\.(cpp|h|hpp|py|txt)
# Having it update the projects with untracked files is kind of bad :p
if git status --porcelain | grep "?? src[\\/]"
then
    echo "File in src directory not added to index!"
    echo
    echo "Either add it, remove it, or modify this"
    echo "script to only check for certain extensions."
    exit 1
fi

python update-vsproj.py
if [ $? != 0 ]
then
    exit 1
fi

git add teippi.vcxproj Teippi.vcxproj.filters

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
